server:
  port: 8001

# mybatis配置
mybatis:
  type-aliases-package: com.lxf.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.116.88.173:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
