server:
  port: 9527

spring:
  application:
    name: spring-cloud-zuul

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,
  instance:
    prefer-ip-address: true
    instance-id: zuul9527


info:
  app.name: spring-cloud-zuul

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  #  禁止原服务id访问
  ignored-services: springcloud-provider-dept
  # 设置统一的访问前缀
  prefix: /hiiro